name: Demo Hydration Check
on: [push]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build CLI
        run: npm run build
      - name: Run demo hydration
        run: node dist/cli.js run demo

  check-prod:
    name: Check Real SSR Build
    runs-on: ubuntu-latest
    needs: demo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build SSR app
        run: npm run build:ssr   # ← adjust to your SSR build command
      - name: Install dependencies
        run: npm ci
      - name: Build CLI
        run: npm run build
      - name: Run hydration check on real output
        run: node dist/cli.js run path/to/your/real-out-folder