name: Demo Hydration Check
on: [push]

jobs:
  demo:
    name: Demo (must detect mismatches)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build CLI
        run: npm run build

      - name: Run demo hydration (expect mismatches)
        run: |
          if node dist/cli.js run demo; then
            echo "❌ Demo did NOT detect any mismatches – this is unexpected!"
            exit 1
          else
            echo "✅ Demo detected mismatches as expected."
            exit 0
          fi